# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from icon import icon_rc

class Ui_MainWindow_File(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1382, 635)
        MainWindow.setStyleSheet("border-radius:4px;\n"
"")
        self.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1161, 591))
        self.frame.setStyleSheet("border-radius: 5px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_1 = QtWidgets.QFrame(self.frame)
        self.frame_1.setGeometry(QtCore.QRect(0, 0, 291, 591))
        self.frame_1.setStyleSheet("QFrame#frame_1{\n"
"    background-color: rgb(123, 169, 255);\n"
"    border-top-left-radius:32px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-right-radius:0px;\n"
"    border-bottom-left-radius:32px;\n"
"}")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.inter_tilte = QtWidgets.QPushButton(self.frame_1)
        self.inter_tilte.setGeometry(QtCore.QRect(0, 10, 281, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.inter_tilte.setFont(font)
        self.inter_tilte.setStyleSheet("border:none;\n"
"color: rgb(255, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/svg/namicailiao.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inter_tilte.setIcon(icon)
        self.inter_tilte.setIconSize(QtCore.QSize(28, 28))
        self.inter_tilte.setObjectName("inter_tilte")
        self.btn_select_win1 = QtWidgets.QPushButton(self.frame_1)
        self.btn_select_win1.setGeometry(QtCore.QRect(0, 480, 291, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_select_win1.setFont(font)
        self.btn_select_win1.setStyleSheet("QPushButton:hover{\n"
"    background-color:rgb(85, 117, 177);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/svg/wenjian-white.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_select_win1.setIcon(icon1)
        self.btn_select_win1.setIconSize(QtCore.QSize(20, 20))
        self.btn_select_win1.setObjectName("btn_select_win1")
        self.label_7 = QtWidgets.QLabel(self.frame_1)
        self.label_7.setGeometry(QtCore.QRect(0, 90, 291, 3))
        self.label_7.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(290, 0, 951, 591))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 951, 41))
        self.frame_4.setStyleSheet("background-color: #f7f8ff;\n"
"border-top-right-radius:32px;\n"
"border-top-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-bottom-left-radius:0px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.min_window = QtWidgets.QPushButton(self.frame_4)
        self.min_window.setGeometry(QtCore.QRect(830, 0, 41, 41))
        self.min_window.setStyleSheet("QPushButton{\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-right-radius:0px;\n"
"    border-bottom-left-radius:0px;\n"
"    color:#928ae1;\n"
"    icon:url(:/svg/zuixiaohua_purple.svg);\n"
"}    \n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 138, 255);\n"
"    border:none;\n"
"    padding: 3px;\n"
"    color: #FFFFFF;\n"
"    icon:url(:/svg/zuixiaohua_white.svg);\n"
"}\n"
"")
        self.min_window.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/svg/minwin.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_window.setIcon(icon2)
        self.min_window.setIconSize(QtCore.QSize(26, 26))
        self.min_window.setObjectName("min_window")
        self.max_window = QtWidgets.QPushButton(self.frame_4)
        self.max_window.setGeometry(QtCore.QRect(870, 0, 41, 41))
        self.max_window.setStyleSheet("QPushButton{\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-right-radius:0px;\n"
"    border-bottom-left-radius:0px;\n"
"    color:#928ae1;\n"
"    icon:url(:/svg/zuidahua_purple.svg);\n"
"}    \n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 138, 255);\n"
"    border:none;\n"
"    padding: 3px;\n"
"    color: #FFFFFF;\n"
"    icon:url(:/svg/zuidahua_white.svg);\n"
"}\n"
"")
        self.max_window.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/svg/maxwin.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max_window.setIcon(icon3)
        self.max_window.setIconSize(QtCore.QSize(26, 26))
        self.max_window.setObjectName("max_window")
        self.close_window = QtWidgets.QPushButton(self.frame_4)
        self.close_window.setGeometry(QtCore.QRect(910, 0, 41, 41))
        self.close_window.setStyleSheet("QPushButton{\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:32px;\n"
"    border-bottom-right-radius:0px;\n"
"    border-bottom-left-radius:0px;\n"
"    color:#928ae1;\n"
"    icon:url(:/svg/guanbi_purple.svg);\n"
"}    \n"
"\n"
"QPushButton:hover{\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:32px;\n"
"    border-bottom-right-radius:0px;\n"
"    border-bottom-left-radius:0px;\n"
"    background-color:rgb(146, 138, 255);\n"
"    border:none;\n"
"    padding: 3px;\n"
"    color: #FFFFFF;\n"
"    icon:url(:/svg/guanbi_white.svg);\n"
"}\n"
"")
        self.close_window.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/svg/close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_window.setIcon(icon4)
        self.close_window.setIconSize(QtCore.QSize(26, 26))
        self.close_window.setObjectName("close_window")
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setGeometry(QtCore.QRect(-1, 39, 951, 551))
        self.frame_2.setStyleSheet("border-top-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-bottom-left-radius:0px;\n"
"background-color: #e7e8f0;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.file_table = QtWidgets.QTableWidget(self.frame_2)
        self.file_table.setGeometry(QtCore.QRect(0, 71, 951, 481))
        self.file_table.setObjectName("file_table")
        self.file_table.setColumnCount(0)
        self.file_table.setRowCount(0)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(250, 10, 441, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1382, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inter_tilte.setText(_translate("MainWindow", " 纳米材料力学性能分析"))
        self.btn_select_win1.setText(_translate("MainWindow", "打开新文件"))
        self.label.setText(_translate("MainWindow", "欢迎使用纳米材料力学性能分析系统"))

